[package]
name = "scr_ext_http"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr_ext_http"
test = false
doctest = false

[dependencies]
scr_core = { path = "../../core" }
mio = { version = "0.8.10", features = ["net", "os-poll"] }
rustls = "0.22.1"
rustls-pemfile = "2.0.0"
pki-types = { package = "rustls-pki-types", version = "1", features = ["std"] }
webpki-roots = "0.26"
thiserror = "1.0.51"
bstr = "1.8.0"
memchr = "2.6.4"
url = "2.5.0"
lazy_static = "1.4.0"
regex = "1.10.2"

[features]
debug_log_http = []
