[package]
name = "scr_ext_http"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr_ext_http"
test = false
doctest = false

[dependencies]
scr_core = { path = "../../core" }
rustls = { version = "0.22.1", features = ["logging"] }
rustls-pemfile = "2.0.0"
mio = { version = "0.8.10", features = ["net", "os-poll"] }
pki-types = { package = "rustls-pki-types", version = "1", features = ["std"] }
webpki-roots = "0.26"
thiserror = "1.0.51"
bstr = "1.8.0"
memchr = "2.6.4"
url = "2.5.0"
lazy_static = "1.4.0"
regex = "1.10.2"

[dev-dependencies]
mockito = "1.2.0"
reqwest = { version = "0.11.23"}
tokio = "1.35.1"
hyper = { version="1.1.0" }
hyper-tls = "0.6.0"
http = "1.0.0"
hyper-util = { version = "0.1.2", default-features = false, features = ["server-auto"] }
http-body-util = "0.1"
tokio-rustls = { version = "0.25", default-features = false }


[features]
debug_log_http = []
