[workspace]
members = ["core", "extensions/sqlite", "extensions/http", "extensions/utils"]

[package]
name = "scr"
version = "0.1.0"
edition = "2021"


[lib]
name = "scr"
# tests are all in scr_core, no need to bloat the output of `cargo test --all`
test = false
doctest = false

[[bin]]
name = "scr"
test = false

[dev-dependencies]
rstest = "0.19.0"
regex = "1.10"
scr_ext_utils = { path = "./extensions/utils" }


[dependencies]
scr_core = { path = "./core", default-features = false }
scr_ext_sqlite = { path = "./extensions/sqlite", optional = true }
scr_ext_http = { path = "./extensions/http", optional = true }
scr_ext_utils = { path = "./extensions/utils", optional = true }


[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release]
panic = "abort"
lto = "thin"

[profile.dev]
panic = "unwind"

[features]
repl = ["scr_core/repl"]
sqlite = ["dep:scr_ext_sqlite"]
http = ["dep:scr_ext_http"]
utils = ["dep:scr_ext_utils"]

default = ["utils"]
full = ["scr_core/full", "repl", "sqlite", "http", "utils"]

unstable = ["scr_core/unstable"]
debug_logging = ["scr_core/debug_logging"]
