[workspace]
members = [
    "core",
    "extensions/sqlite",
    "extensions/http",
    "extensions/utils",
    "extensions/python",
]

[package]
name = "scr"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

license = "MIT"
repository = "https://github.com/cmrschwarz/scr"

[lib]
name = "scr"
# tests are all in scr_core, no need to bloat the output of `cargo test --all`
test = false
doctest = false
path = "src/lib.rs" # the default, workaround https://github.com/webern/cargo-readme/issues/32

[[bin]]
name = "scr"
test = false
path = "src/main.rs" # the default, workaround https://github.com/webern/cargo-readme/issues/32

[dev-dependencies]
rstest = "0.21.0"
regex = "1.10"
scr_ext_utils = { path = "./extensions/utils" }


[dependencies]
scr_core = { path = "./core", default-features = false }
scr_ext_sqlite = { path = "./extensions/sqlite", optional = true }
scr_ext_python = { path = "./extensions/python", optional = true }
scr_ext_http = { path = "./extensions/http", optional = true }
scr_ext_utils = { path = "./extensions/utils", optional = true }
once_cell = "1.19.0"


[profile.release]
panic = "abort"
lto = "thin"

[profile.dev]
panic = "unwind"

[profile.bench]
inherits = "release"
debug = true

[features]
repl = ["scr_core/repl"]
sqlite = ["dep:scr_ext_sqlite"]
python = ["dep:scr_ext_python"]
http = ["dep:scr_ext_http"]
utils = ["dep:scr_ext_utils"]

default = ["utils"]
full = ["scr_core/full", "repl", "sqlite", "http", "utils", "python"]

unstable = ["scr_core/unstable"]
debug_logging = ["scr_core/debug_logging"]
