[package]
name = "scr"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr"

[[bin]]
name = "scr"

[[test]]
path = "tests/lib.rs"
name = "integration"

[[bench]]
name = "bench"
path = "bench/lib.rs"

[dependencies]

# disabled
# crossbeam = "0.8.2"
# fantoccini = "0.19.0"
# html5ever = "0.26.0"
# indexmap = "1.9.3"
# itertools = "0.11.0"
# markup5ever_rcdom = "0.2.0"
# num = "0.4.0"
# url = "2.3.1"

# REPL:
reedline = { version = "0.22.0", features = ["bashisms"] }
shlex = "1.1.0"

# utils
bstr = "1.5.0"
lazy_static = "1.4.0"
memchr = "2.5.0"
num-traits = "0.2.16"
static_assertions = "1.1.0"
thiserror = "1.0.38"

# small size / layout optimizations
arrayvec = "0.7.3"
bitvec = "1.0"
nonmax = "0.5.3"
smallstr = { version = "0.3.0", features = ["union"] }
smallvec = { version = "1.10.0", features = ["union", "write"] }
thin-vec = "0.2.12"

# features for core operators
encoding_rs = { version = "0.8.32", features = ["fast-legacy-encode"] }
rand = "0.8.5"
regex = "1.7.1"
regex-syntax = "0.7.2"
uuid = { version = "1.4.0", features = ["v4", "fast-rng"] }

[dev-dependencies]
rstest = "0.18.1"

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release]
panic = "abort"
lto = "thin"

[profile.dev]
panic = "unwind"

[features]
unstable = []
debug_logging = []
