[package]
name = "scr"
version = "0.1.0"
edition = "2021"

[dependencies]
html5ever = "0.26.0"
markup5ever_rcdom = "0.2.0"
fantoccini="0.19.0"
smallvec =  { version= "1.10.0", features = ["union"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
crossbeam = "0.8.2"

[lib]
name = "libscr"
path = "src/lib.rs"

[[bin]]
name = "scr"
path = "src/main.rs"
