[workspace]
members = ["core", "ext_sqlite"]

[package]
name = "scr"
version = "0.1.0"
edition = "2021"


[lib]
name = "scr"
test = false
doctest = false

[[bin]]
name = "scr"
test = false


[dependencies]
scr_core = { path = "./core", default-features = false }
scr_ext_sqlite = {path="./ext_sqlite", optional = true}

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release]
panic = "abort"
lto = "thin"

[profile.dev]
panic = "unwind"

[features]
repl = ["scr_core/repl"]

sqlite = ["dep:scr_ext_sqlite"]

default = []
full = ["scr_core/full", "repl", "sqlite"]

unstable = ["scr_core/unstable"]
debug_logging = ["scr_core/debug_logging"]
