[package]
name = "scr"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr"

[[bin]]
name = "scr"

[[test]]
path = "tests/lib.rs"
name = "integration"

[[bench]]
name = "bench"
path = "bench/lib.rs"

[dependencies]
# html5ever = "0.26.0"
markup5ever_rcdom = "0.2.0"
fantoccini = "0.19.0"
smallvec = { version = "1.10.0", features = ["union"] }
smallstr = "0.3.0"
crossbeam = "0.8.2"
lazy_static = "1.4.0"
regex = "1.7.1"
regex-syntax = "0.7.2"
bstr = "1.5.0"
num = "0.4.0"
thiserror = "1.0.38"
url = "2.3.1"
indexmap = "1.9.3"
nonmax = "0.5.3"
is-terminal = "0.4.7"
arrayvec = "0.7.3"
static_assertions = "1.1.0"
rand = "0.8.5"
itertools = "0.11.0"

[dependencies.encoding_rs]
version = "0.8.32"
features = ["fast-legacy-encode"]

[dependencies.uuid]
version = "1.4.0"
features = ["v4", "fast-rng"]

[dev-dependencies]
rstest="0.18.1"

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release]
panic = "abort"
lto = "thin"

[features]
unstable = []
debug_logging = []
