[workspace]
members = ["core", "extensions/sqlite", "extensions/http", "extensions/misc_cmds"]

[package]
name = "scr"
version = "0.1.0"
edition = "2021"


[lib]
name = "scr"
test = false
doctest = false

[[bin]]
name = "scr"
test = false


[dependencies]
scr_core = { path = "./core", default-features = false }
scr_ext_sqlite = {path="./extensions/sqlite", optional = true}
scr_ext_http = {path="./extensions/http", optional = true}
scr_ext_misc_cmds = {path="./extensions/misc_cmds", optional = true}

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release]
panic = "abort"
lto = "thin"

[profile.dev]
panic = "unwind"

[features]
repl = ["scr_core/repl"]
sqlite = ["dep:scr_ext_sqlite"]
http = ["dep:scr_ext_http"]
misc_cmds = ["dep:scr_ext_misc_cmds"]

default = []
full = ["scr_core/full", "repl", "sqlite", "http", "misc_cmds",]

unstable = ["scr_core/unstable"]
debug_logging = ["scr_core/debug_logging"]
