[package]
name = "scr_ext_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr_ext_python"
test = false
doctest = false

[dependencies]
scr_core = { path = "../../core" }
pyo3 = { version = "0.21.2", features = [] }
