[package]
name = "scr_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr_core"


[dependencies]
# utils
bstr = { version = "1.9.1", default-features = false }
lazy_static = "1.4.0"
memchr = "2.7.2"
static_assertions = "1.1.0"
thiserror = "1.0.58"
derive_more = "0.99.17"

# small size / layout optimizations
arrayvec = "0.7.4"
bitvec = { version = "1.0", features = ["std"], default-features = false }
#nonmax = "0.5.5"
smallstr = { version = "0.3.0", features = ["union"] }
smallvec = { version = "1.13.2", features = ["union", "write"] }
thin-vec = "0.2.13"
indexmap = "2.2.6"

# features for core operators / types
num = "0.4.2"
encoding_rs = { version = "0.8.34", features = ["fast-legacy-encode"] }
regex = "1.10.4"
regex-syntax = "0.8.3"
unicode-ident = "1.0.12"

# deps for repl mode:
[dependencies.reedline]
version = "0.27.1"
features = ["bashisms"]
default-features = false
optional = true

[dependencies.shlex]
version = "1.3.0"
default-features = false
optional = true


[dev-dependencies]
rstest = "0.19.0"

[features]
default = []

repl = ["dep:shlex", "dep:reedline"]
full = ["repl"]

unstable = []

debug_logging = []
cow_field_logging = []
output_field_logging = []
action_group_logging = []
iter_state_logging = []
