[package]
name = "scr_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr_core"

[dependencies]

# disabled
# crossbeam = "0.8.2"
# fantoccini = "0.19.0"
# html5ever = "0.26.0"
# indexmap = "1.9.3"
# itertools = "0.11.0"
# markup5ever_rcdom = "0.2.0"
# num = "0.4.0"
# url = "2.3.1"
# uuid = { version = "1.4.0", features = ["v4", "fast-rng"] }

# repl:
reedline = { version = "0.22.0", features = ["bashisms"], default-features = false, optional = true}
shlex = { version = "1.1.0", default-features = false, optional = true}

# utils
bstr = {version = "1.5.0", default-features = false }
lazy_static = "1.4.0"
memchr = "2.5.0"
static_assertions = "1.1.0"
thiserror = "1.0.38"

# num for BigInt / BigRational / the PrimInt trait
num-bigint = "0.4.1"
num-rational="0.4.1"
num-traits = "0.2.16"

# small size / layout optimizations
arrayvec = "0.7.3"
bitvec = { version = "1.0", features = ["std"], default-features = false }
nonmax = "0.5.3"
smallstr = { version = "0.3.0", features = ["union"] }
smallvec = { version = "1.10.0", features = ["union", "write"] }
thin-vec = "0.2.12"
indexmap = "1.9.3"

# features for core operators
encoding_rs = { version = "0.8.32", features = ["fast-legacy-encode"] }
regex = "1.7.1"
regex-syntax = "0.7.2"


[dev-dependencies]
rstest = "0.18.1"

[features]
default = []

repl = ["dep:shlex", "dep:reedline"]

full = ["repl"]

unstable = []
debug_logging = []
