[package]
name = "scr_core"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

license = "MIT"
repository = "https://github.com/cmrschwarz/scrr/tree/main/core"

[lib]
name = "scr_core"


[dependencies]
# utils
bstr = { version = "1.9.1", features = ["alloc"], default-features = false }
once_cell = "1.19.0"
memchr = "2.7.2"
static_assertions = "1.1.0"
thiserror = "1.0.61"
derive_more = "0.99.17"
ref-cast = "1.0.23"
subenum = "1.1.2"
metamatch = "0.2.3"


# small size / layout optimizations
arrayvec = "0.7.4"
bitvec = { version = "1.0", features = ["std"], default-features = false }
#nonmax = "0.5.5"
smallstr = { version = "0.3.0", features = ["union"] }
smallvec = { version = "1.13.2", features = ["union", "write"] }
thin-vec = "0.2.13"
indexmap = "2.2.6"

# features for core operators / types
num = "0.4.3"
encoding_rs = { version = "0.8.34", features = ["fast-legacy-encode"] }
regex = "1.10.4"
regex-syntax = "0.8.3"
unicode-ident = "1.0.12"

# for debug_log
handlebars = { git = "https://github.com/cmrschwarz/handlebars-rust.git", branch = "fix_indent_after_if" }
#handlebars = "5.1.2"
serde_json = "1.0.117"
serde_derive = "1.0.203"

# deps for repl mode:
[dependencies.reedline]
version = "0.32.0"
features = ["bashisms"]
default-features = false
optional = true

[dependencies.shlex]
version = "1.3.0"
default-features = false
optional = true


[dev-dependencies]
rstest = "0.21.0"

[features]
default = []

repl = ["dep:shlex", "dep:reedline"]
full = ["repl"]

unstable = []
debug_logging = []
liveness_analysis_logging = ["debug_logging"]
stream_logging = ["debug_logging"]
cow_field_logging = ["debug_logging"]
output_field_logging = ["debug_logging"]
field_action_logging = ["debug_logging"]
field_action_group_logging = ["debug_logging"]
iter_state_logging = ["output_field_logging", "field_action_logging"]
field_action_group_accel_logging = ["debug_logging"]
