[package]
name = "scr_ext_utils"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

license = "MIT"
repository = "https://github.com/cmrschwarz/scrr/tree/main/extensions/utils"

[lib]
name = "scr_ext_utils"
test = false
doctest = false

[dependencies]
scr_core = { path = "../../core" }
bstr = { version = "1.9.1", default-features = false }
primes = "0.3.0"
num = "0.4.3"
indexmap = "2.2.6"

[dev-dependencies]
scr = { path = "../../", features = ["utils"] }
rstest = "0.20.0"
