[package]
name = "scr_ext_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "scr_ext_utils"
test = false
doctest = false

[dependencies]
scr_core = { path = "../../core" }
bstr = { version = "1.8.0", default-features = false }
primes = "0.3.0"
num = "0.4.1"
indexmap = "2.1.0"

[dev-dependencies]
scr = { path = "../../", features = ["utils"] }
rstest = "0.18.2"
